server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-server
              uri: lb://user-server
              predicates:
                - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/