server:
  port: 8081
spring:
  application:
    name: user-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: User Service
    description: ERP User Management Service
    version: 1.0.0   